### ISSUE TITLE
Zigbee error logged on startup - Investigate

### ISSUE THREAD

**Issue by shortbloke** [shortbloke/home_assistant_config#38]
```
2020-01-12 23:56:50 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 86, in _initialize
    epr = await self.zdo.Active_EP_req(self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.7/site-packages/zigpy/util.py", line 88, in retry
    r = await func()
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 191, in request
    result = await asyncio.wait_for(req.result, timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by shortbloke** [comment]
Debug level logs collected and question asked on Zigpy github project: https://github.com/zigpy/zigpy/issues/277

**Comment by Adminiuga** [comment]
can you enable debug logging for:
```
bellows.zigbee.application: debug
bellows.api: debug
```
and collect logs from the startup. And let's move this to https://github.com/zigpy/bellows as it belong there

**Comment by shortbloke** [comment]
Updated debug logs collected and issue recreated: https://github.com/zigpy/bellows/issues/207
I don't have permission to move issues.

**Comment by shortbloke** [comment]
Issue caused by old device "00:0d:6f:00:12:35:22:91" in ZigBee database. Deleted from all tables using SQLite Web HassIO addon to provide access to the database. 
Thanks @Adminiuga
